### ISSUE TITLE
Parameter Value Error Overlap

### ISSUE THREAD

**Issue by cosinewaves** [cameronpcampbell/Ignite#1]
When having a parameter instance with a Validation and it's not met, the outline of the box's red outline is covered by a row below. (Sorry for bad explaining, see below);
![image](https://github.com/user-attachments/assets/fae78e3c-64c7-4dfb-9aa8-2222baf52bda)
it works fine when you select it;
![image](https://github.com/user-attachments/assets/2f3f4c10-3a7b-493b-b4ed-317de9ea5706)

```lua
Scope:Map {
	Header = { Text = "Parameters" },
	Sections = {
		{ Key = "Scale", Value = { Text = "0", Validation = "%d+" } },
		{ Key = "Name", Value = "CoolName" } :: any,
		{ Key = "Type", Value = "MyType" } :: any,
	}
},
```

**Comment by cameronpcampbell** [comment]
hey i didnt see this issue until now. That definitely isn't right.
